BOOX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('auth/', include('authentication.urls')),
    path('profile/', include('profilepage.urls')),
    path('readers-favorite/', include('readers_favorite.urls')),
<<<<<<< HEAD
<<<<<<< HEAD
    path('add_review/', include ('add_review.urls')),
    path('editreview/', include ('editreview.urls')),
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
    path('bookmarks/', include('bookmarks.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

authentication/urls.py
from django.urls import path
from .views import register, login_user, logout_user, flutter_login, flutter_register, flutter_logout

app_name = 'authentication'

urlpatterns = [
  path('register/', register, name='register'),
  path('login/', login_user, name='login'), 
  path('logout/', logout_user, name='logout'),
  path('flutter_login/', flutter_login, name='flutter_login'),
  path('flutter_register/', flutter_register, name='flutter_register'),
  path('flutter_logout/', flutter_logout, name='flutter_logout'),
]

readers_favorite/urls.py
from django.urls import path
from landing_page.views import get_data_json

from readers_favorite.views import add_comment, add_comment_flutter, add_upvote_ajax, get_all_comments, get_commenters, get_username_by_id, show_readers_favorite

app_name = 'readers_favorite'

urlpatterns = [
    path('', show_readers_favorite, name='show_readers_favorite'),
    path("get_data_json/", get_data_json, name="get_data_json"),
    path('add_upvote_ajax/<int:item_id>/', add_upvote_ajax, name='add_upvote_ajax'),
    path('get_username_by_id/<int:user_id>/', get_username_by_id, name='get_username_by_id'),
    path('get_all_comments/', get_all_comments, name='get_all_comments'),
    path('get_commenters/', get_commenters, name='get_commenters'),
    path('add_comment/', add_comment, name='add_comment'),
    path('add_comment_flutter/<str:user_name>/', add_comment_flutter, name='add_comment_flutter'),
]

readers_favorite/models.py
from django.db import models
from django.contrib.auth.models import User
<<<<<<< HEAD
<<<<<<< HEAD
from django.utils import timezone
=======
from django.utils import timezone  # Import the timezone module
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
=======
from django.utils import timezone  # Import the timezone module
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394

class ReadersFavorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_contribution = models.IntegerField(default=0)

class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_comment = models.CharField(default="enter comment (max 100)", max_length=100)
<<<<<<< HEAD
<<<<<<< HEAD
    timestamp = models.DateTimeField(default=timezone.now) 
=======
    timestamp = models.DateTimeField(default=timezone.now) 
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
=======
    timestamp = models.DateTimeField(default=timezone.now) 
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394

readers_favorite/views.py
import json
from django.db.models import F
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, render
from landing_page.models import Books
from readers_favorite.models import ReadersFavorite, Comments
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Sum
from django.contrib.auth.models import User

def show_readers_favorite(request):
    books = Books.objects.all()

    if request.user.is_authenticated:
        user = request.user  # Get the current user
        all_comments = Comments.objects.all()
        user_contribution = Comments.objects.filter(user=user).count()

        # Try to get the user's existing ReadersFavorite or create a new one
        user_selected, created = ReadersFavorite.objects.get_or_create(user=user, user_contribution = user_contribution)

        response = {
            'books': books,
            'user_is_authenticated' : request.user.is_authenticated,
            'all_comments': all_comments,
        }
        return render(request, "readers_favorite.html", response)
    else:
        response = {
            'books': books,
        }
        return render(request, "readers_favorite.html", response)

def get_all_comments(request):
    data = Comments.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_username_by_id(request, user_id):
    try:
        user = User.objects.get(id=user_id)
        username = user.username
        return JsonResponse({'username': username})
    except User.DoesNotExist:
        return HttpResponseNotFound("User not found")


def get_commenters(request):
    data = ReadersFavorite.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


@csrf_exempt
def add_upvote_ajax(request, item_id):
    if request.method == 'POST':
        book_selected = get_object_or_404(Books, id=item_id)
        book_selected.total_upvotes += 1
        book_selected.save()
        # Return a JSON response to update the client-side data
        response_data = {'success': True}
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    return HttpResponseNotFound()

@csrf_exempt
def add_comment(request):
    if request.method == 'POST' and request.user.is_authenticated:
        user_comment = request.POST.get("user_comment")

        # Ensure a valid User instance
        user, created = User.objects.get_or_create(username=request.user.username)

        new_comment = Comments(user=user, user_comment=user_comment)
        new_comment.save()

        # Increment user_contribution by 1 for the current user
        ReadersFavorite.objects.filter(user=user).update(user_contribution=F('user_contribution') + 1)

        return HttpResponse("CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def add_comment_flutter(request, user_name):
    if request.method == 'POST':
        user_comment = request.POST.get("user_comment")

        # Ensure a valid User instance
        user, created = User.objects.get_or_create(username=user_name)

        new_comment = Comments(user=user, user_comment=user_comment)
        new_comment.save()

        # Increment user_contribution by 1 for the current user
        ReadersFavorite.objects.filter(user=user).update(user_contribution=F('user_contribution') + 1)

        return HttpResponse("CREATED", status=201)

    return HttpResponseNotFound()

readers_favorite/templates/readers_favorite_base.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="page-content">

        <!-- ***** Banner Start ***** -->
        <div class="main-banner">
          <div class="row">
            <div class="col-lg-7">
              <div class="header-text">
                <!-- <h6>Welcome To BOOX</h6> -->
                <h4><em>VIEW</em> Our Readers Favorites Books </h4>
                <div class="main-button">
                  <!-- <a href="browse.html">Browse Now</a> -->
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ***** Banner End ***** -->


        <!-- ***** Details Start ***** -->
        <div class="game-details">
          <div class="row">
            <div class="col-lg-12">
              <h2>Our Readers top 10 voted books!</h2>
            </div>
            <div class="col-lg-12">
              <div class="content">
                <div class="row">
                  <div class="col-lg-12" style="text-align: center;">
                    <p>Here you can view this month's top 10 most reviewed books by our readers!</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ***** Details End ***** -->

          <!-- Most upvotes Start -->
          <div id="most-upvotes"></div>
          <br>
          <br>
          <!-- Most upvotes End -->

          <div class="col-lg-12" style="text-align: center;">
            <div class="heading-section">
              <h4><em>Login Now</em> to Join Our Comment Section!</h4>
            </div>
          </div>

          <div class="main-button" style="text-align: center;">
            <a href="{% url 'authentication:login' %}">Login</a>
          </div>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2036 <a href="#">Cyborg Gaming</a> Company. All rights reserved. 
          
          <br>Design: <a href="https://templatemo.com" target="_blank" title="free CSS templates">TemplateMo</a>  Distributed By <a href="https://themewagon.com" target="_blank" >ThemeWagon</a></p>
        </div>
      </div>
    </div>
  </footer>


  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

  <script src="assets/js/isotope.min.js"></script>
  <script src="assets/js/owl-carousel.js"></script>
  <script src="assets/js/tabs.js"></script>
  <script src="assets/js/popup.js"></script>
  <script src="assets/js/custom.js"></script>

  <script>

    async function getBookInfo() {
      return fetch("{% url 'readers_favorite:get_data_json' %}").then((response) => response.json());
    }

    async function refreshFavoriteBooks() {
      console.log('Fetching data...');
      document.getElementById("most-upvotes").innerHTML = "";
      const BooksAll = await getBookInfo();

      // Sort the BooksAll array based on most reviewed (for top 10) in descending order
      BooksAll.sort((a, b) => b.fields.total_reviews - a.fields.total_reviews);

      // Limit the array to the top 10 books
      const top10Books = BooksAll.slice(0, 10);

      // Sort the top10 Books based on upvotes
      top10Books.sort((a, b) => b.fields.total_upvotes - a.fields.total_upvotes);

      let htmlString = ``; // Initialize the HTML string
      number = 0;
      top10Books.forEach((book) => {
        let bookTitle = book.fields.title;
        let bookAuthor = book.fields.author;

        bookTitle = (bookTitle.length > 25) ? bookTitle.substring(0, 25) + "..." : bookTitle
        bookAuthor = (bookAuthor.length > 20) ? bookAuthor.substring(0, 20) + "..." : bookAuthor

        number += 1;
        htmlString += `
          <div class="gaming-library profile-library">
            <div class="col-lg-12">
              <div class="item">
                <h4>No. ${number}</h4>
                <br>
                <ul>
                  <li><img src="${book.fields.image_url_s}" alt="" class="templatemo-item"></li>
                  <li><h4>Title</h4><span>${bookTitle}<span></li>
                  <li><h4>Author</h4><span>${bookAuthor}<span></li>
                  <li><h4>Total Reviews</h4><span>${book.fields.total_reviews}<span></li>
                  <li><h4>Total Upvotes</h4><span>${book.fields.total_upvotes}<span></li>
                </ul>
              </div>
            </div>
          </div>
        `;
      });

      document.getElementById("most-upvotes").innerHTML = htmlString;

    }

    refreshFavoriteBooks();
</script>
  


{% endblock content %}