BOOX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('auth/', include('authentication.urls')),
    path('profile/', include('profilepage.urls')),
    path('readers-favorite/', include('readers_favorite.urls')),
<<<<<<< HEAD
<<<<<<< HEAD
    path('add_review/', include ('add_review.urls')),
    path('editreview/', include ('editreview.urls')),
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
    path('bookmarks/', include('bookmarks.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

add_review/urls.py
from add_review.views import *
from django.urls import path 

app_name = 'add_review'

urlpatterns= [
    path('add_review_ajax/', add_review_ajax, name='add_review_ajax'),
    path('show_review/<int:book_id>/', show_review, name='show_review'),
    path('get_reviews/<int:book_id>', get_reviews, name='get_reviews'),
    path('get_review_by_user/<int:book_id>', get_review_by_user, name='get_review_by_user'),
    path('get_username/<int:book_id>', get_username, name='get_username'),
    path('delete-review-flutter/<int:idReview>/', delete_review_flutter, name='delete_review_flutter'),
]

editreview/urls.py
from django.urls import path

from editreview.views import *
# from .views import show_main
# from main.views import show_main, create_product
# from main.views import show_main, create_product, show_xml 
# from main.views import show_main, create_product, show_xml, show_json
# from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, get_product_json, add_product_ajax
# from main.views import register #sesuaikan dengan nama fungsi yang dibuat
# from main.views import login_user #sesuaikan dengan nama fungsi yang dibuat
# from main.views import logout_user
# from main.views import edit_product
# from main.views import delete_product


app_name = 'editreview'

urlpatterns = [
    # path('', show_main, name='show_main'),
    # path('xml/', show_xml, name='show_xml'), 
    # path('json/', show_json, name='show_json'),
    # path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    # path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    # path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    # path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat
    # path('logout/', logout_user, name='logout'),
    path('<int:id>/', editreview, name='editreview'),
    path('edit-review-flutter/', editreviewflutter, name='editreviewflutter'),
    path('add-reply/<str:user_name>/', add_reply, name='add_reply'),
    path('get-reply/<idReview>/', get_reply, name='get_reply'),
    path('delete-reply/<idReply>/', delete_reply_flutter, name='delete_reply_flutter'),
    # path('delete/<int:id>', delete_product, name='delete_product'), # sesuaikan dengan nama fungsi yang dibuat
    # path('get-product/', get_product_json, name='get_product_json'),
    # path('create-product-ajax/', add_product_ajax, name='add_product_ajax')
    path('get-review/<int:review_id>', get_review, name="get_review"),
    path('reviews/', display_reviews, name='display_reviews'),
    path("", get_review, name="get_review"),
    path('edit-review-ajax/', edit_review_ajax, name='edit_review_ajax'),

]

landing_page/urls.py
from django.urls import path
from .views import *

app_name = "landing_page"

urlpatterns = [
    path("", get_books, name="get_books"),
    path("page/", show_landing_page, name="show_landing_page"),
    path("get_data_json/", get_data_json, name="get_data_json"),
    path("check_if_user_logged_in/", check_if_user_logged_in, name="check_if_user_logged_in"),
    path("get_faq_data/", get_faq_data, name="get_faq_data"),
    path("faq/data/", show_faq_data_json, name="show_faq_data_json"),
    path("faq/data/user/", get_faq_data_per_user, name="get_faq_data_per_user"),
    path("faq/question/", add_faq_question, name="add_faq_question"),
    path("faq/edit/<int:pk>/", edit_question, name="edit_faq_question"),
    path("faq/delete/<int:pk>/", delete_question, name="delete_faq_question"),
]

add_review/models.py
from django.db import models

# Create your models here.

add_review/forms.py
from django.forms import ModelForm
from add_review.models import * 
from editreview.models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ["review", "rating"]

add_review/views.py
from django.shortcuts import render
from landing_page.models import Books
from django.http import HttpResponseRedirect
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from add_review.forms import ReviewForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from editreview.models import *
from django.views.decorators.csrf import csrf_exempt, csrf_protect

# Create your views here.
def add_review(request,book_id):
    book = Books.objects.filter(pk=book_id)
    form = ReviewForm(request.POST or None)

    book_instance = Books.objects.get(pk=book_id)
    form.instance.book = book_instance
    if form.is_valid() and request.method == "POST": 
        form.instance.user = request.user
        form.instance.book = book_instance
        form.save()
        return HttpResponseRedirect(reverse('add_review:show_review'))
    
    context = {'form':form,
               'book':book[0]}
    return render (request, "add_review.html", context)

def get_reviews(request, book_id):
    book = Books.objects.get(pk=book_id)
    data = Review.objects.filter(book=book)
    return HttpResponse(serializers.serialize("json", data))

@login_required(login_url='authentication:login')
def get_review_by_user(request, book_id):
    book = Books.objects.get(pk=book_id)
    data = Review.objects.filter(user=request.user, book=book)
    return HttpResponse(serializers.serialize("json", data))

@login_required(login_url='authentication:login')
def show_review(request, book_id):
    book = Books.objects.filter(pk=book_id)
    reviews = Review.objects.filter(book=book_id).order_by('-created_at')
    context = {
        'reviews':reviews,
        'user':request.user,
        'book':book[0]
        }
    return render(request, "show_review.html", context)

def get_username(request, book_id):
    book = Books.objects.get(pk=book_id)
    reviews = Review.objects.filter(book=book)
    usernames = [review.user.username for review in reviews]

    return JsonResponse({"fields": usernames})

@csrf_exempt
def add_review_ajax(request):
    if request.method == 'POST':
        book_pk = request.POST.get('book')
        book = Books.objects.get(pk=book_pk)
        if Review.objects.filter(user=request.user, book=book).exists():
            return HttpResponse(b"ALREADY EXISTS", status=200)
        
        user = request.user
        review = request.POST.get('review')
        rating = request.POST.get('rating')

        new_review = Review.objects.create(book=book, user=user, review=review, rating=rating)

        book.total_ratings += int(rating)
        book.total_reviews += 1

        print(book.total_ratings)
        book.save()
        new_review.save()
        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_review_flutter(request, idReview):
    if request.method == 'DELETE':
        try:
            review = Review.objects.get(pk=idReview, user=request.user)
            book = review.book
            book.total_ratings -= review.rating
            review.delete()
            return JsonResponse({"status": "success"}, status=200)
        except review.DoesNotExist:
            return JsonResponse({"status": "error", "message": "Review not found"}, status=404)

    return JsonResponse({"status": "error", "message": "Invalid request"}, status=400)

add_review/templates/add_review.html
<!-- The Modal -->
<div class="modal fade" id="review-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" style="color: rgb(245, 50, 82);">Write Your Review</h5>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
              <form id="review-form" method="post">
                  {% csrf_token %}
                  <!-- form fields start -->
                  <div class="form-group">
                      <label for="rating">Stars:</label>
                      <select class="form-control" id="rating" name="rating">
                          <option value="1">1</option>
                          <option value="2">2</option>
                          <option value="3">3</option>
                          <option value="4">4</option>
                          <option value="5">5</option>
                      </select>
                  </div>
                  <div class="form-group">
                    <label for="review">Add Your Review:</label>
                    <textarea type="text" class="form-control" id="review" name="review" rows="5"></textarea>
                  </div>
                  <div class="form-group" style="display: none;">
                    <input type="text" class="form-control" id="book" name="book" disabled="disabled" value="{{ book.pk }}">
                  </div>
                  <!-- form fields end -->
              </form>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" id="cancel-modal" data-dismiss="modal">Cancel</button>
              <button type="button" class="btn btn-primary submit-review" id="submit-modal">Submit</button>
          </div>
      </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

add_review/templates/show_review.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Book Review Page</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <style>
            body {
                background-color: #f7f7f7;
            }

            .book-details {
                background-color: #fff;
                padding: 20px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                border-radius: 8px;
            }

            .book-image {
                max-width: 200px;
                height: auto;
            }

            .user-review {
                background-color: #fff;
                margin-top: 20px;
                padding: 15px;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            }
        </style>
{% endblock meta %}

{% block content %}

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4">
                <div class="book-details">
                    <div style="text-align: center;">
                        <img src="{{ book.image_url_l }}" alt="Book Cover" class="book-image">
                    </div>
                    <h2 class="mt-3"> {{ book.title }}</h2>
                    <p><strong>Author:</strong> {{ book.author }}</p>
                    <p><strong>Release Year:</strong> {{ book.year }}</p>
                    <p><strong>Publisher:</strong> {{ book.publisher }}</p>
                    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
                    <p><strong>Total Reviews:</strong> {{ book.total_reviews }}</p>

                </div>
                <div class="user-review">
                </div>

                <!-- Add Review Button -->
                <button class="btn btn-primary add-review" id="open-modal-link" data-toggle="modal" data-target="#review-modal">Add Review</button>
                <!-- Edit My Review Button -->
                <a id="edit-review"><button type="submit" class="btn btn-secondary edit-review">Edit My Review</button></a>
                </div>

            <div class="col-md-8">
                <h2>User Reviews</h2>
                
                <!-- Loop through all reviews -->
                <div class="user-review" id="user-reviews">
                </div>
                <!-- End Loop -->

            </div>
        </div>
    </div>

    <!-- Add Review Modal -->
    {% include 'add_review.html' %}
    <!-- End Add Review Modal -->
    
    <script>
        
        async function loadCurrentUserReviewData(){
            let url = "{% url 'add_review:get_review_by_user' 0 %}".replace("0", "{{ book.pk }}");
            return fetch(url).then(response => response.json());
        }
        
        
        async function loadUserReviewsData(book_pk){
            let url = "{% url 'add_review:get_reviews' 0 %}".replace("0", book_pk)
            return fetch(url).then(response => response.json())
        }
        
        async function getUsername(book_id){
            let url = "{% url 'add_review:get_username' 0 %}".replace("0", book_id)
            return fetch(url).then(response => response.json())
        }

        async function refreshUserReviews(){
            const userReviews = await loadUserReviewsData("{{ book.pk }}")
            const userReviewsDiv = document.getElementById('user-reviews')
            let usernames_json = await getUsername("{{ book.pk }}")
            const usernames = usernames_json.fields
            userReviewsDiv.innerHTML = ''
            let i=0;
            if (userReviews.length > 0) {
                userReviews.forEach(userReview => {
                    const userReviewDiv = document.createElement('div')
                    let username = usernames[i++]
                    userReviewDiv.classList.add('user-review')
                    let stars = ""
                    for (let i=0; i < userReview.fields.rating; i++) {
                        stars += "★"
                    }

                    while (stars.length < 5) {
                        stars += "☆"
                    }
                    userReviewDiv.innerHTML = `
                        <h4>${username}</h4>
                        <h6>${userReview.fields.created_at}</h6>
                        <div class="review-stars">
                            ${stars}
                        </div>
                        <p>${userReview.fields.review}</p>
                    `
                    userReviewsDiv.appendChild(userReviewDiv)
                    
                })
            } else {
                const noReviewDiv = document.createElement('div')
                noReviewDiv.innerHTML = `
                    <h4>There are no reviews for this book yet.</h4>
                `
                userReviewsDiv.appendChild(noReviewDiv)
            }
        }

        async function refreshMyReview(){
            const userReviews = await loadCurrentUserReviewData()
            const myReviewDiv = document.querySelector('.user-review')
            myReviewDiv.innerHTML = '<h2>User Review</h2>'

            if (userReviews.length !== 0) {
                const userReview = userReviews[0]
                let stars = ""
                for (let i=0; i < userReview.fields.rating; i++) {
                    stars += "★"
                }

                while (stars.length < 5) {
                    stars += "☆"
                }

                HtmlString = `
                    <h2>Your Review</h2>
                    <h4>{{ user.username }}</h4>
                    <h6>${userReview.fields.created_at}</h6>
                    <div class="review-stars">
                        ${stars}
                    </div>
                    <p>${userReview.fields.review}</p>
                `

                document.querySelector('.add-review').style.display = 'none'
                document.querySelector('.edit-review').style.display = 'block'

                // EDIT REVIEW //
                document.querySelector('#edit-review').setAttribute('href', "{% url 'editreview:get_review' 0 %}".replace("0", userReview.pk))                // EDIT REVIEW //

            } else {
                HtmlString = `
                    <h4>You have not reviewed this book yet.</h4>
                `
                document.querySelector('.add-review').style.display = 'block'
                document.querySelector('.edit-review').style.display = 'none'
            }

            myReviewDiv.innerHTML = HtmlString
        }

        async function refreshPage(){
            await refreshUserReviews()
            await refreshMyReview()
        }

        async function addReview(){
            let formData = new FormData(document.querySelector('#review-form'))
            formData.append('book', "{{ book.pk }}")
            fetch("{% url 'add_review:add_review_ajax' %}", {
                method: "POST",
                body: formData
            }).then(refreshPage)
            document.querySelector('#cancel-modal').click()
        }

        refreshPage()
        document.querySelector('.submit-review').addEventListener('click', addReview)
        document.getElementById("home-nav").setAttribute("href","{% url 'landing_page:show_landing_page' %}")
    </script>
{% endblock content %}