BOOX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('auth/', include('authentication.urls')),
    path('profile/', include('profilepage.urls')),
    path('readers-favorite/', include('readers_favorite.urls')),
<<<<<<< HEAD
<<<<<<< HEAD
    path('add_review/', include ('add_review.urls')),
    path('editreview/', include ('editreview.urls')),
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
    path('bookmarks/', include('bookmarks.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

authentication/urls.py
from django.urls import path
from .views import register, login_user, logout_user, flutter_login, flutter_register, flutter_logout

app_name = 'authentication'

urlpatterns = [
  path('register/', register, name='register'),
  path('login/', login_user, name='login'), 
  path('logout/', logout_user, name='logout'),
  path('flutter_login/', flutter_login, name='flutter_login'),
  path('flutter_register/', flutter_register, name='flutter_register'),
  path('flutter_logout/', flutter_logout, name='flutter_logout'),
]

landing_page/urls.py
from django.urls import path
from .views import *

app_name = "landing_page"

urlpatterns = [
    path("", get_books, name="get_books"),
    path("page/", show_landing_page, name="show_landing_page"),
    path("get_data_json/", get_data_json, name="get_data_json"),
    path("check_if_user_logged_in/", check_if_user_logged_in, name="check_if_user_logged_in"),
    path("get_faq_data/", get_faq_data, name="get_faq_data"),
    path("faq/data/", show_faq_data_json, name="show_faq_data_json"),
    path("faq/data/user/", get_faq_data_per_user, name="get_faq_data_per_user"),
    path("faq/question/", add_faq_question, name="add_faq_question"),
    path("faq/edit/<int:pk>/", edit_question, name="edit_faq_question"),
    path("faq/delete/<int:pk>/", delete_question, name="delete_faq_question"),
]

profilepage/urls.py
from django.urls import path
from profilepage.views import *

app_name = 'profilepage'

urlpatterns = [
    path('', show_profile, name='show_profile'),
    path('create/', create_profile, name='create_profile'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('edit/', edit_profile_ajax, name='edit_profile'),
    path('get-profile/', get_profile_json, name='get_profile_json'),
    path('edit-flutter/', edit_profile_flutter, name= 'edit_profile_flutter'),
    path('create-flutter/<str:user_name>/', create_profile_flutter, name= 'create_profile_flutter'),
]

readers_favorite/urls.py
from django.urls import path
from landing_page.views import get_data_json

from readers_favorite.views import add_comment, add_comment_flutter, add_upvote_ajax, get_all_comments, get_commenters, get_username_by_id, show_readers_favorite

app_name = 'readers_favorite'

urlpatterns = [
    path('', show_readers_favorite, name='show_readers_favorite'),
    path("get_data_json/", get_data_json, name="get_data_json"),
    path('add_upvote_ajax/<int:item_id>/', add_upvote_ajax, name='add_upvote_ajax'),
    path('get_username_by_id/<int:user_id>/', get_username_by_id, name='get_username_by_id'),
    path('get_all_comments/', get_all_comments, name='get_all_comments'),
    path('get_commenters/', get_commenters, name='get_commenters'),
    path('add_comment/', add_comment, name='add_comment'),
    path('add_comment_flutter/<str:user_name>/', add_comment_flutter, name='add_comment_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        
        <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


        <title>BooX - Awesome Book Website</title>
    
        <!-- Additional CSS Files -->
        <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}"> 
        <link rel="stylesheet" href="{% static 'css/templatemo-cyborg-gaming.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>


        <!-- ***** Preloader Start ***** -->
        <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
            <span></span>
            <span></span>
            <span></span>
            </div>
        </div>
        </div>
        <!-- ***** Preloader End ***** -->

        <!-- ***** Header Area Start ***** -->
        <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{% url 'landing_page:show_landing_page' %}" class="logo">
                            <img src="{% static 'images/logo.png' %}" alt="BooX">
                        </a>
                        <!-- ***** Logo End ***** -->

                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a href="#" class="active">Home</a></li>
                            <li><a href="#user-faq">Help</a></li>
                            <li><a href="{% url 'authentication:logout' %}" id="login-logout">Logout</a></li>
                            <li><a href="{% url 'readers_favorite:show_readers_favorite' %}">Readers Favorite</a></li>
                            <li><a href="{% url 'profilepage:show_profile' %}">Profile</a></li>
                        </ul>   
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
        </header>
        <!-- ***** Header Area End ***** -->
<<<<<<< HEAD
    </head>

    <body>
        <!-- ***** Preloader Start ***** -->
        <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
            <span></span>
            <span></span>
            <span></span>
            </div>
        </div>
        </div>
        <!-- ***** Preloader End ***** -->

        <!-- ***** Header Area Start ***** -->
        <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{% url 'landing_page:show_landing_page' %}" class="logo">
                            <img src="{% static 'images/logo.png' %}" alt="BooX">
                        </a>
                        <!-- ***** Logo End ***** -->

                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a href="#" class="active">Home</a></li>
                            <li><a href="#user-faq">Help</a></li>
                            <li><a href="{% url 'authentication:logout' %}" id="login-logout">Logout</a></li>
                            <li><a href="{% url 'readers_favorite:show_readers_favorite' %}">Readers Favorite</a></li>
                            <li><a href="{% url 'profilepage:show_profile' %}">Profile <img src="{%static 'images/profile-header.jpg'%}" alt=""></a></li>
                        </ul>   
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
        </header>
        <!-- ***** Header Area End ***** -->
=======
>>>>>>> 439082c7645e65b3e365cf5c45e76b847d95f394
    </head>

    <body>
        {% block content %}
        {% endblock content %}

        <!-- Scripts -->
        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/isotope.min.js' %}"></script>
        <script src="{% static 'js/owl-carousel.js' %}"></script>
        <script src="{% static 'js/tabs.js' %}"></script>
        <script src="{% static 'js/popup.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
    </body>
</html>